config/routes.rb
Rails.application.routes.draw do

  resources :telefonos

  root 'main_pages#home'

  
  
  

  devise_for :users
  resources :users, :only => [:show, :edit, :update, :destroy]
  post 'users/:id' => 'users#find'
  resources :contactos, :only => [:create, :new, :edit, :show, :update, :destroy]

  namespace :api, defaults: { format: :json }  do
    scope module: :v1 do
      resources :users, only: [:show]
      resources :contactos, only: [:show]
    end
  end
end

app/models/contacto.rb
class Contacto < ActiveRecord::Base
  mount_uploader :foto, ImageUploader
  belongs_to :user
  belongs_to :tipo
  has_many :telefonos, :dependent => :destroy
  accepts_nested_attributes_for :telefonos, allow_destroy: true,
                                :reject_if => lambda { |a| a[:numero].blank? }


  before_save { self.email = email.downcase }
  validates :nombre, presence: true, length: { maximum: 50 }
  validates :apellidos, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :tipo_id, presence: true

end

app/controllers/api/v1/contactos_controller.rb
class Api::V1::ContactosController < Api::V1::BaseController
  def show
    contacto = Contacto.find(params[:id])

    render(json: Api::V1::ContactoSerializer.new(contacto).to_json)
  end
end

app/controllers/contactos_controller.rb
class ContactosController < ApplicationController
  before_filter :authenticate_user!
  
  before_action :set_contacto, only: [:show, :edit, :update, :destroy]

  before_filter :check_user, only: [:show, :edit, :update, :destroy]

  # GET /contactos
  # GET /contactos.json
  def index
    @contactos = Contacto.all
  end

  # GET /contactos/1
  # GET /contactos/1.json
  def show
  end

  # GET /contactos/new
  def new
    @contacto = Contacto.new
    @tipos = Tipo.all
    @contacto.telefonos.build
  end

  # GET /contactos/1/edit
  def edit
    @tipos = Tipo.all
    @contacto.telefonos.build
  end

  # POST /contactos
  # POST /contactos.json
  def create
    @contacto = Contacto.new(contacto_params)
    @contacto.user = current_user
    @tipos = Tipo.all

    respond_to do |format|
      if @contacto.save
        format.html { redirect_to @contacto, notice: 'Se ha creado el contacto correctamente.' }
        format.json { render :show, status: :created, location: @contacto }
      else
        format.html { render :new }
        format.json { render json: @contacto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contactos/1
  # PATCH/PUT /contactos/1.json
  def update
    respond_to do |format|
      if @contacto.update(contacto_params)
        format.html { redirect_to @contacto, notice: 'Se ha actualizado el contacto correctamente.' }
        format.json { render :show, status: :ok, location: @contacto }
      else
        format.html { render :edit }
        format.json { render json: @contacto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contactos/1
  # DELETE /contactos/1.json
  def destroy
    @contacto.destroy
    respond_to do |format|
      format.html { redirect_to current_user, notice: 'Se ha eliminado el contacto correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contacto
      @contacto = Contacto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contacto_params
      params.require(:contacto).permit(:nombre, :apellidos, :email, :foto, :user_id, :tipo_id, :remove_foto, telefonos_attributes: [ :id, :numero ])
    end

    def check_user
      redirect_to current_user, alert: "Prohibido acceso a contactos de otro usuario!" if current_user.contactos.exclude?(@contacto)
    end

end

app/helpers/contactos_helper.rb
module ContactosHelper
end

app/views/contactos/_form.html.erb
<%= form_for(@contacto) do |f| %>
  <% if @contacto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contacto.errors.count, "error") %> prohibited this contacto from being saved:</h2>

      <ul>
      <% @contacto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellidos %><br>
    <%= f.text_field :apellidos %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :foto %><br>
    <%= f.file_field :foto %>
    <% if f.object.foto? %>
      <%= image_tag f.object.foto.thumb.url %>
      <%= f.label :remove_foto %>
      <%= f.check_box :remove_foto %> 
    <% end %>
  </div>
  <div class="radio_button">
    <%= f.label :tipo_id %><br>
    <% @tipos.each do |tipo| %>
      <% if @contacto.tipo == tipo %>
        <%= f.radio_button :tipo_id, tipo.id, :checked => true %> 
      <% else %>
        <%= f.radio_button :tipo_id, tipo.id %>
      <% end %>
      <%= label tipo.tipo, tipo.tipo %><br>
    <% end %>
  </div>
   Telefonos:
  <div class="field">
    <%= f.fields_for :telefonos do |t| %>
      <div class="field">
        <%= t.label :numero %><br>
        <%= t.number_field :numero %>
      </div>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contactos/edit.html.erb
<h1>Editing Contacto</h1>

<%= render 'form' %>

<%= link_to 'Eliminar', @contacto, method: :delete, data: { confirm: 'Estas seguro?' } %> |
<%= link_to 'Atras', current_user %>

app/views/contactos/index.html.erb
<h1>Listing Contactos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellidos</th>
      <th>Email</th>
      <th>Foto</th>
      <th>Tipo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contactos.each do |contacto| %>
      <tr>
        <td><%= contacto.nombre %></td>
        <td><%= contacto.apellidos %></td>
        <td><%= contacto.email %></td>
        <td><%= image_tag contacto.foto.thumb.url %></td>
        <td><%= contacto.tipo.tipo %></td>
        <td><%= link_to 'Show', contacto %></td>
        <td><%= link_to 'Edit', edit_contacto_path(contacto) %></td>
        <td><%= link_to 'Destroy', contacto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contacto', new_contacto_path %>

app/views/contactos/new.html.erb
<h1>New Contacto</h1>

<%= render 'form' %>

<%= link_to 'Atras', current_user %>

app/views/contactos/show.html.erb
<p>
  <strong>Nombre:</strong>
  <%= @contacto.nombre %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @contacto.apellidos %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contacto.email %>
</p>

<p>
  <strong>Foto:</strong>
  <%= image_tag @contacto.foto.thumb.url %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @contacto.tipo.tipo %>
</p>

<p>
  <strong>Telefono(s):</strong>
    <% @contacto.telefonos.each do |telefono| %>
      <br/><%= telefono.numero %>
    <% end %>
</p>

<%= link_to 'Editar', edit_contacto_path(@contacto) %> |
<%= link_to 'Atras', current_user %>