config/routes.rb
Rails.application.routes.draw do

  resources :telefonos

  root 'main_pages#home'

  
  
  

  devise_for :users
  resources :users, :only => [:show, :edit, :update, :destroy]
  post 'users/:id' => 'users#find'
  resources :contactos, :only => [:create, :new, :edit, :show, :update, :destroy]

  namespace :api, defaults: { format: :json }  do
    scope module: :v1 do
      resources :users, only: [:show]
      resources :contactos, only: [:show]
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :contactos, :dependent => :destroy
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
  def show
    user = User.find(params[:id])

    render(json: Api::V1::UserSerializer.new(user).to_json)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_user, only: [:show, :find, :edit, :update, :destroy]
  before_filter :check_user, only: [:show, :find, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @contactos = @user.contactos.paginate(page: params[:page], :per_page => 10)
  end

  def find
    @contactos = @user.contactos.where("lower(nombre) LIKE ? OR lower(apellidos) LIKE ?", "%#{params[:nombre].downcase}%", "%#{params[:nombre].downcase}%").paginate(page: params[:page], :per_page => 10)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Se ha creado el usuario correctamente.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Se ha actualizado el usuario correctamente.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Se ha eliminado el usuario correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end


    def check_user
      redirect_to current_user, alert: "Prohibido acceso a otro usuario!" if current_user != User.find(params[:id])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Back', @user %>

app/views/users/find.html.erb
<p>
  <strong>e-mail:</strong>
  <%= @user.email %>
  <%= link_to 'Editar', edit_user_registration_path %>
</p>

<h1>Contactos:</h1>

<%= will_paginate @contactos %>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellidos</th>
      <th>Email</th>
      <th>Foto</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @contactos.each do |contacto| %>
      <tr>
        <td><%= contacto.nombre %></td>
        <td><%= contacto.apellidos %></td>
        <td><%= contacto.email %></td>
        <td><%= image_tag contacto.foto.thumb.url %></td>
        <td><%= link_to 'Ver', contacto %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @contactos %>

<%= link_to 'Ver todos', current_user %>

<%= link_to 'Nuevo contacto', new_contacto_path %>

<h2>Buscador:</h2>

<%= form_tag(current_user, :method => "post") do %>
    <%= label_tag(:nombre, "Introduce nombre o apellidos:") %>
    <%= text_field_tag(:nombre) %>
    <%= submit_tag("Buscar") %>
<% end %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>e-mail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Atras', users_path %>

app/views/users/show.html.erb
<p>
  <strong>e-mail:</strong>
  <%= @user.email %>
  <%= link_to 'Editar', edit_user_registration_path %>
</p>

<h1>Contactos:</h1>

<%= will_paginate @contactos %>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellidos</th>
      <th>Email</th>
      <th>Foto</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @contactos.each do |contacto| %>
      <tr>
        <td><%= contacto.nombre %></td>
        <td><%= contacto.apellidos %></td>
        <td><%= contacto.email %></td>
        <td><%= image_tag contacto.foto.thumb.url %></td>
        <td><%= link_to 'Ver', contacto %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @contactos %>

<%= link_to 'Nuevo contacto', new_contacto_path %>

<h2>Buscador:</h2>

<%= form_tag(current_user, :method => "post") do %>
    <%= label_tag(:nombre, "Introduce nombre o apellidos:") %>
    <%= text_field_tag(:nombre) %>
    <%= submit_tag("Buscar") %>
<% end %>