config/routes.rb
Rails.application.routes.draw do

  resources :telefonos

  root 'main_pages#home'

  
  
  

  devise_for :users
  resources :users, :only => [:show, :edit, :update, :destroy]
  post 'users/:id' => 'users#find'
  resources :contactos, :only => [:create, :new, :edit, :show, :update, :destroy]

  namespace :api, defaults: { format: :json }  do
    scope module: :v1 do
      resources :users, only: [:show]
      resources :contactos, only: [:show]
    end
  end
end

app/models/telefono.rb
class Telefono < ActiveRecord::Base
  belongs_to :contacto
end

app/controllers/telefonos_controller.rb
class TelefonosController < ApplicationController
  before_action :set_telefono, only: [:show, :edit, :update, :destroy]

  # GET /telefonos
  # GET /telefonos.json
  def index
    @telefonos = Telefono.all
  end

  # GET /telefonos/1
  # GET /telefonos/1.json
  def show
  end

  # GET /telefonos/new
  def new
    @telefono = Telefono.new
  end

  # GET /telefonos/1/edit
  def edit
  end

  # POST /telefonos
  # POST /telefonos.json
  def create
    @telefono = Telefono.new(telefono_params)

    respond_to do |format|
      if @telefono.save
        format.html { redirect_to @telefono, notice: 'Telefono was successfully created.' }
        format.json { render :show, status: :created, location: @telefono }
      else
        format.html { render :new }
        format.json { render json: @telefono.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /telefonos/1
  # PATCH/PUT /telefonos/1.json
  def update
    respond_to do |format|
      if @telefono.update(telefono_params)
        format.html { redirect_to @telefono, notice: 'Telefono was successfully updated.' }
        format.json { render :show, status: :ok, location: @telefono }
      else
        format.html { render :edit }
        format.json { render json: @telefono.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /telefonos/1
  # DELETE /telefonos/1.json
  def destroy
    @telefono.destroy
    respond_to do |format|
      format.html { redirect_to telefonos_url, notice: 'Telefono was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_telefono
      @telefono = Telefono.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def telefono_params
      params.require(:telefono).permit(:numero, :contacto_id)
    end
end

app/helpers/telefonos_helper.rb
module TelefonosHelper
end

app/views/telefonos/_form.html.erb
<%= form_for(@telefono) do |f| %>
  <% if @telefono.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@telefono.errors.count, "error") %> prohibited this telefono from being saved:</h2>

      <ul>
      <% @telefono.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :numero %><br>
    <%= f.number_field :numero %>
  </div>
  <div class="field">
    <%= f.label :contacto_id %><br>
    <%= f.text_field :contacto_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/telefonos/edit.html.erb
<h1>Editing Telefono</h1>

<%= render 'form' %>

<%= link_to 'Show', @telefono %> |
<%= link_to 'Back', telefonos_path %>

app/views/telefonos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Telefonos</h1>

<table>
  <thead>
    <tr>
      <th>Numero</th>
      <th>Contacto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @telefonos.each do |telefono| %>
      <tr>
        <td><%= telefono.numero %></td>
        <td><%= telefono.contacto %></td>
        <td><%= link_to 'Show', telefono %></td>
        <td><%= link_to 'Edit', edit_telefono_path(telefono) %></td>
        <td><%= link_to 'Destroy', telefono, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Telefono', new_telefono_path %>

app/views/telefonos/new.html.erb
<h1>New Telefono</h1>

<%= render 'form' %>

<%= link_to 'Back', telefonos_path %>

app/views/telefonos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numero:</strong>
  <%= @telefono.numero %>
</p>

<p>
  <strong>Contacto:</strong>
  <%= @telefono.contacto %>
</p>

<%= link_to 'Edit', edit_telefono_path(@telefono) %> |
<%= link_to 'Back', telefonos_path %>